# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: false
r_check_args: --as-cran
latex: false

r:
  - release
  - devel

dist: xenial

repos:
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

r_packages:
  - devtools

r_github_packages:
  - jimhester/lintr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - gdal-bin
      - libgdal-dev
      - libcurl4-openssl-dev

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'


after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
