# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: false
r_check_args: --as-cran
latex: false

r:
  - release
  - devel

dist: xenial

r_packages:
  - devtools

r_github_packages:
  - jimhester/lintr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - gdal-bin
      - libgdal-dev
      - libcurl4-openssl-dev

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
