# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false

r:
  - release
  - devel

dist: trusty

r_packages:
  - devtools
  - sf

r_github_packages:
  - jimhester/lintr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
