# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

r:
  - release
  - devel

dist: xenial

r_packages:
  - devtools
  - sf

r_github_packages:
  - jimhester/lintr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libcurl4-openssl-dev

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
